### ISSUE TITLE
urllib3.connectionpool - Failed to parse headers 错误

### ISSUE THREAD

**Issue by qiushui777** [xiaoheiwo/GGSCAN#1]
在扫描过程中，我经常遇到这种错误导致扫描停止。

>  urllib3.connectionpool - Failed to parse headers (url=): [MissingHeaderBodySeparatorDefect()], unparsed data: 'MIME - Version: 1.1\r\nServer: Lanswitch - V100R003 HttpServer 1.1\r\nDate: FRI, 11 Jan 2002 15:02:59\r\nConnection: close\r\nContent-Type: text/html\r\nLast-Modified: Fri, 21 Jul 2006 09:36:36 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'MIME - Version: 1.1\r\nServer: Lanswitch - V100R003 HttpServer 1.1\r\nDate: FRI, 11 Jan 2002 15:02:59\r\nConnection: close\r\nContent-Type: text/html\r\nLast-Modified: Fri, 21 Jul 2006 09:36:36 GMT\r\n\r\n'

这一点很奇怪，因为我看到GGtitle.py中以及catch了except。

**Comment by xiaoheiwo** [comment]
抱歉这么久没有回复你信息，这个工具目前已经弃用了。关于你这个问题 你是否扫描的时候开启了代理，建议关闭代理

**Comment by qiushui777** [comment]
感谢回复，我发现这个错误并不影响扫描。。。这个工具我感觉其实不错啊，我在你这个上面改了改，相比其他工具至少代码简单，方便扩展。。

**Comment by xiaoheiwo** [comment]
感谢老哥支持 后续看具体情况要不要继续更新
