### ISSUE TITLE
gg.py 一直寻找mscan_result

### ISSUE THREAD

**Issue by wumingzhilian** [xiaoheiwo/GGSCAN#5]
![image](https://user-images.githubusercontent.com/69114599/134296284-1b141b22-2f61-4ee3-968d-9c2b6bded2db.png)
您好，全部安装完成之后，运行仍然报错。

**Comment by xiaoheiwo** [comment]
你好 您的masscan应该是没有设置到环境变量里面  导致调用的时候找不到masscan
